# Generated by Django 5.0.14 on 2025-12-03 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_profile_avatar_url_alter_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationlink',
            options={'verbose_name': 'Донат-ссылка', 'verbose_name_plural': 'Донат-ссылки'},
        ),
        migrations.AddField(
            model_name='resource',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='archive.category'),
        ),
    ]
