# Generated by Django 5.0.14 on 2025-12-01 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archive', '0002_resource_uploaded_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(blank=True)),
                ('readme', models.TextField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Публичный'), ('private', 'Приватный'), ('unlisted', 'По ссылке')], default='public', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('related_materials', models.ManyToManyField(blank=True, related_name='projects', to='archive.resource')),
                ('tags', models.ManyToManyField(blank=True, related_name='projects', to='archive.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
