# Generated by Django 5.0.14 on 2025-12-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_resource_uploaded_file'),
        ('hub', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='archive.tag'),
        ),
    ]
