# Generated by Django 5.0.14 on 2025-12-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='project_files/'),
        ),
    ]
